# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\PLASMINFORGE\Dropbox\Apps\DiyWeatherStation\WeatherStation\main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 480))
        MainWindow.setMaximumSize(QtCore.QSize(800, 480))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.Dashboard = QtWidgets.QWidget()
        self.Dashboard.setObjectName("Dashboard")
        self.gridLayout = QtWidgets.QGridLayout(self.Dashboard)
        self.gridLayout.setContentsMargins(4, 4, 4, 4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_2 = QtWidgets.QFrame(self.Dashboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("border: 0px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setLineWidth(0)
        self.frame_2.setObjectName("frame_2")
        self.frame_7 = QtWidgets.QFrame(self.frame_2)
        self.frame_7.setGeometry(QtCore.QRect(0, 0, 394, 223))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setStyleSheet("border: 0px;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setLineWidth(0)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_10 = QtWidgets.QFrame(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_10.sizePolicy().hasHeightForWidth())
        self.frame_10.setSizePolicy(sizePolicy)
        self.frame_10.setStyleSheet("")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_7.setContentsMargins(30, 30, 30, 30)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_16 = QtWidgets.QLabel(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("images/humidity.png"))
        self.label_16.setScaledContents(True)
        self.label_16.setWordWrap(False)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_7.addWidget(self.label_16)
        self.horizontalLayout_6.addWidget(self.frame_10)
        self.frame_11 = QtWidgets.QFrame(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_11.sizePolicy().hasHeightForWidth())
        self.frame_11.setSizePolicy(sizePolicy)
        self.frame_11.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_11.setStyleSheet("")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_11)
        self.gridLayout_4.setContentsMargins(20, 0, 0, 0)
        self.gridLayout_4.setHorizontalSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.minHumFeild = QtWidgets.QLabel(self.frame_11)
        self.minHumFeild.setObjectName("minHumFeild")
        self.gridLayout_4.addWidget(self.minHumFeild, 3, 1, 1, 1)
        self.currenthumFeild = QtWidgets.QLabel(self.frame_11)
        self.currenthumFeild.setObjectName("currenthumFeild")
        self.gridLayout_4.addWidget(self.currenthumFeild, 1, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 3, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 0, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 1, 0, 1, 1)
        self.maxHumFeild = QtWidgets.QLabel(self.frame_11)
        self.maxHumFeild.setObjectName("maxHumFeild")
        self.gridLayout_4.addWidget(self.maxHumFeild, 0, 1, 1, 1)
        self.horizontalLayout_6.addWidget(self.frame_11)
        self.gridLayout.addWidget(self.frame_2, 1, 2, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.Dashboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setStyleSheet("border: 0px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_3.setObjectName("frame_3")
        self.frame_15 = QtWidgets.QFrame(self.frame_3)
        self.frame_15.setGeometry(QtCore.QRect(0, 0, 394, 223))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_15.sizePolicy().hasHeightForWidth())
        self.frame_15.setSizePolicy(sizePolicy)
        self.frame_15.setStyleSheet("border: 0px;")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setLineWidth(0)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_16 = QtWidgets.QFrame(self.frame_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_16.sizePolicy().hasHeightForWidth())
        self.frame_16.setSizePolicy(sizePolicy)
        self.frame_16.setStyleSheet("")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_11.setContentsMargins(30, 30, 30, 30)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_24 = QtWidgets.QLabel(self.frame_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setText("")
        self.label_24.setPixmap(QtGui.QPixmap("images/wind.png"))
        self.label_24.setScaledContents(True)
        self.label_24.setWordWrap(False)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_11.addWidget(self.label_24)
        self.horizontalLayout_10.addWidget(self.frame_16)
        self.frame_17 = QtWidgets.QFrame(self.frame_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_17.sizePolicy().hasHeightForWidth())
        self.frame_17.setSizePolicy(sizePolicy)
        self.frame_17.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_17.setStyleSheet("")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_17)
        self.gridLayout_6.setContentsMargins(20, 0, 0, 0)
        self.gridLayout_6.setHorizontalSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.windDirectFeild = QtWidgets.QLabel(self.frame_17)
        self.windDirectFeild.setObjectName("windDirectFeild")
        self.gridLayout_6.addWidget(self.windDirectFeild, 3, 1, 1, 1)
        self.windSpeedFeild = QtWidgets.QLabel(self.frame_17)
        self.windSpeedFeild.setObjectName("windSpeedFeild")
        self.gridLayout_6.addWidget(self.windSpeedFeild, 1, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.frame_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_6.addWidget(self.label_25, 3, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.frame_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout_6.addWidget(self.label_26, 0, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.frame_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout_6.addWidget(self.label_27, 1, 0, 1, 1)
        self.windGustFeild = QtWidgets.QLabel(self.frame_17)
        self.windGustFeild.setObjectName("windGustFeild")
        self.gridLayout_6.addWidget(self.windGustFeild, 0, 1, 1, 1)
        self.horizontalLayout_10.addWidget(self.frame_17)
        self.gridLayout.addWidget(self.frame_3, 2, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.Dashboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("border: 0px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setGeometry(QtCore.QRect(0, 0, 394, 223))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setStyleSheet("border: 0px;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setLineWidth(0)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setStyleSheet("")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_4.setContentsMargins(30, 30, 30, 30)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("images/temp.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.horizontalLayout.addWidget(self.frame_6)
        self.frame_18 = QtWidgets.QFrame(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_18.sizePolicy().hasHeightForWidth())
        self.frame_18.setSizePolicy(sizePolicy)
        self.frame_18.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_18.setStyleSheet("")
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_18)
        self.gridLayout_2.setContentsMargins(20, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.minTempFeild = QtWidgets.QLabel(self.frame_18)
        self.minTempFeild.setObjectName("minTempFeild")
        self.gridLayout_2.addWidget(self.minTempFeild, 3, 1, 1, 1)
        self.currentTempFeild = QtWidgets.QLabel(self.frame_18)
        self.currentTempFeild.setObjectName("currentTempFeild")
        self.gridLayout_2.addWidget(self.currentTempFeild, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 3, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 0, 1, 1)
        self.maxTempFeild = QtWidgets.QLabel(self.frame_18)
        self.maxTempFeild.setObjectName("maxTempFeild")
        self.gridLayout_2.addWidget(self.maxTempFeild, 0, 1, 1, 1)
        self.horizontalLayout.addWidget(self.frame_18)
        self.gridLayout.addWidget(self.frame, 1, 1, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.Dashboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setStyleSheet("border: 0px;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setLineWidth(-1)
        self.frame_4.setObjectName("frame_4")
        self.frame_12 = QtWidgets.QFrame(self.frame_4)
        self.frame_12.setGeometry(QtCore.QRect(0, 0, 394, 223))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_12.sizePolicy().hasHeightForWidth())
        self.frame_12.setSizePolicy(sizePolicy)
        self.frame_12.setStyleSheet("border: 0px;")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setLineWidth(0)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_13 = QtWidgets.QFrame(self.frame_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_13.sizePolicy().hasHeightForWidth())
        self.frame_13.setSizePolicy(sizePolicy)
        self.frame_13.setStyleSheet("")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_9.setContentsMargins(30, 30, 30, 30)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_20 = QtWidgets.QLabel(self.frame_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap("images/rain.png"))
        self.label_20.setScaledContents(True)
        self.label_20.setWordWrap(False)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_9.addWidget(self.label_20)
        self.horizontalLayout_8.addWidget(self.frame_13)
        self.frame_14 = QtWidgets.QFrame(self.frame_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_14.sizePolicy().hasHeightForWidth())
        self.frame_14.setSizePolicy(sizePolicy)
        self.frame_14.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_14.setStyleSheet("")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_14)
        self.gridLayout_5.setContentsMargins(20, 0, 0, 0)
        self.gridLayout_5.setHorizontalSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.nightRainFeild = QtWidgets.QLabel(self.frame_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.nightRainFeild.sizePolicy().hasHeightForWidth())
        self.nightRainFeild.setSizePolicy(sizePolicy)
        self.nightRainFeild.setObjectName("nightRainFeild")
        self.gridLayout_5.addWidget(self.nightRainFeild, 2, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.frame_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_5.addWidget(self.label_22, 1, 0, 1, 1)
        self.dayRainFeild = QtWidgets.QLabel(self.frame_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.dayRainFeild.sizePolicy().hasHeightForWidth())
        self.dayRainFeild.setSizePolicy(sizePolicy)
        self.dayRainFeild.setObjectName("dayRainFeild")
        self.gridLayout_5.addWidget(self.dayRainFeild, 1, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.frame_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_5.addWidget(self.label_23, 2, 0, 1, 1)
        self.spacer = QtWidgets.QFrame(self.frame_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.spacer.sizePolicy().hasHeightForWidth())
        self.spacer.setSizePolicy(sizePolicy)
        self.spacer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.spacer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.spacer.setObjectName("spacer")
        self.gridLayout_5.addWidget(self.spacer, 3, 1, 1, 1)
        self.spacer2 = QtWidgets.QFrame(self.frame_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.spacer2.sizePolicy().hasHeightForWidth())
        self.spacer2.setSizePolicy(sizePolicy)
        self.spacer2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.spacer2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.spacer2.setObjectName("spacer2")
        self.gridLayout_5.addWidget(self.spacer2, 0, 1, 1, 1)
        self.horizontalLayout_8.addWidget(self.frame_14)
        self.gridLayout.addWidget(self.frame_4, 2, 2, 1, 1)
        self.stackedWidget.addWidget(self.Dashboard)
        self.Daily_Graphs = QtWidgets.QWidget()
        self.Daily_Graphs.setObjectName("Daily_Graphs")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Daily_Graphs)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tempDailyGraph = PlotWidget(self.Daily_Graphs)
        self.tempDailyGraph.setObjectName("tempDailyGraph")
        self.gridLayout_3.addWidget(self.tempDailyGraph, 0, 0, 1, 1)
        self.humDailyGraph = PlotWidget(self.Daily_Graphs)
        self.humDailyGraph.setObjectName("humDailyGraph")
        self.gridLayout_3.addWidget(self.humDailyGraph, 0, 1, 1, 1)
        self.windDailyGraph = PlotWidget(self.Daily_Graphs)
        self.windDailyGraph.setObjectName("windDailyGraph")
        self.gridLayout_3.addWidget(self.windDailyGraph, 1, 0, 1, 1)
        self.rainDailyGraph = PlotWidget(self.Daily_Graphs)
        self.rainDailyGraph.setObjectName("rainDailyGraph")
        self.gridLayout_3.addWidget(self.rainDailyGraph, 1, 1, 1, 1)
        self.stackedWidget.addWidget(self.Daily_Graphs)
        self.Weekly_Graphs = QtWidgets.QWidget()
        self.Weekly_Graphs.setObjectName("Weekly_Graphs")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.Weekly_Graphs)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.tempWeeklyGraph = PlotWidget(self.Weekly_Graphs)
        self.tempWeeklyGraph.setObjectName("tempWeeklyGraph")
        self.gridLayout_7.addWidget(self.tempWeeklyGraph, 0, 0, 1, 1)
        self.humWeeklyGraph = PlotWidget(self.Weekly_Graphs)
        self.humWeeklyGraph.setObjectName("humWeeklyGraph")
        self.gridLayout_7.addWidget(self.humWeeklyGraph, 0, 1, 1, 1)
        self.windWeeklyGraph = PlotWidget(self.Weekly_Graphs)
        self.windWeeklyGraph.setObjectName("windWeeklyGraph")
        self.gridLayout_7.addWidget(self.windWeeklyGraph, 1, 0, 1, 1)
        self.rainWeeklyGraph = PlotWidget(self.Weekly_Graphs)
        self.rainWeeklyGraph.setObjectName("rainWeeklyGraph")
        self.gridLayout_7.addWidget(self.rainWeeklyGraph, 1, 1, 1, 1)
        self.stackedWidget.addWidget(self.Weekly_Graphs)
        self.Yearly_Graphs = QtWidgets.QWidget()
        self.Yearly_Graphs.setObjectName("Yearly_Graphs")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.Yearly_Graphs)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.tempYearlyGraph = PlotWidget(self.Yearly_Graphs)
        self.tempYearlyGraph.setObjectName("tempYearlyGraph")
        self.gridLayout_8.addWidget(self.tempYearlyGraph, 0, 0, 1, 1)
        self.humYearlyGraph = PlotWidget(self.Yearly_Graphs)
        self.humYearlyGraph.setObjectName("humYearlyGraph")
        self.gridLayout_8.addWidget(self.humYearlyGraph, 0, 1, 1, 1)
        self.windYearlyGraph = PlotWidget(self.Yearly_Graphs)
        self.windYearlyGraph.setObjectName("windYearlyGraph")
        self.gridLayout_8.addWidget(self.windYearlyGraph, 1, 0, 1, 1)
        self.rainYearlyGraph = PlotWidget(self.Yearly_Graphs)
        self.rainYearlyGraph.setObjectName("rainYearlyGraph")
        self.gridLayout_8.addWidget(self.rainYearlyGraph, 1, 1, 1, 1)
        self.stackedWidget.addWidget(self.Yearly_Graphs)
        self.All_Time_Graphs = QtWidgets.QWidget()
        self.All_Time_Graphs.setObjectName("All_Time_Graphs")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.All_Time_Graphs)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.tempAlltimeGraph = PlotWidget(self.All_Time_Graphs)
        self.tempAlltimeGraph.setObjectName("tempAlltimeGraph")
        self.gridLayout_9.addWidget(self.tempAlltimeGraph, 0, 0, 1, 1)
        self.humAlltimeGraph = PlotWidget(self.All_Time_Graphs)
        self.humAlltimeGraph.setObjectName("humAlltimeGraph")
        self.gridLayout_9.addWidget(self.humAlltimeGraph, 0, 1, 1, 1)
        self.windAlltimeGraph = PlotWidget(self.All_Time_Graphs)
        self.windAlltimeGraph.setObjectName("windAlltimeGraph")
        self.gridLayout_9.addWidget(self.windAlltimeGraph, 1, 0, 1, 1)
        self.rainAlltimeGraph = PlotWidget(self.All_Time_Graphs)
        self.rainAlltimeGraph.setObjectName("rainAlltimeGraph")
        self.gridLayout_9.addWidget(self.rainAlltimeGraph, 1, 1, 1, 1)
        self.stackedWidget.addWidget(self.All_Time_Graphs)
        self.Settings = QtWidgets.QWidget()
        self.Settings.setObjectName("Settings")
        self.formLayoutWidget = QtWidgets.QWidget(self.Settings)
        self.formLayoutWidget.setGeometry(QtCore.QRect(90, 40, 531, 351))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.formLayoutWidget)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dateTimeEdit)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.pushButton_6 = QtWidgets.QPushButton(self.Settings)
        self.pushButton_6.setGeometry(QtCore.QRect(640, 410, 75, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.Settings)
        self.pushButton_7.setGeometry(QtCore.QRect(540, 410, 75, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_8 = QtWidgets.QLabel(self.Settings)
        self.label_8.setGeometry(QtCore.QRect(0, 0, 91, 16))
        self.label_8.setObjectName("label_8")
        self.stackedWidget.addWidget(self.Settings)
        self.horizontalLayout_2.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setMovable(False)
        self.toolBar.setAllowedAreas(QtCore.Qt.TopToolBarArea)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionDashboard = QtWidgets.QAction(MainWindow)
        self.actionDashboard.setObjectName("actionDashboard")
        self.actionDaily_Graphs = QtWidgets.QAction(MainWindow)
        self.actionDaily_Graphs.setObjectName("actionDaily_Graphs")
        self.actionWeekly_Graphs = QtWidgets.QAction(MainWindow)
        self.actionWeekly_Graphs.setObjectName("actionWeekly_Graphs")
        self.actionYearly_Graphs = QtWidgets.QAction(MainWindow)
        self.actionYearly_Graphs.setObjectName("actionYearly_Graphs")
        self.actionAll_Time_Graphs = QtWidgets.QAction(MainWindow)
        self.actionAll_Time_Graphs.setObjectName("actionAll_Time_Graphs")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setCheckable(False)
        self.actionSettings.setObjectName("actionSettings")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.toolBar.addAction(self.actionDashboard)
        self.toolBar.addAction(self.actionDaily_Graphs)
        self.toolBar.addAction(self.actionWeekly_Graphs)
        self.toolBar.addAction(self.actionYearly_Graphs)
        self.toolBar.addAction(self.actionAll_Time_Graphs)
        self.toolBar.addAction(self.actionSettings)
        self.toolBar.addAction(self.actionExit)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Weather Station"))
        self.minHumFeild.setText(_translate("MainWindow", "TextLabel"))
        self.currenthumFeild.setText(_translate("MainWindow", "TextLabel"))
        self.label_17.setText(_translate("MainWindow", "Minimum:"))
        self.label_18.setText(_translate("MainWindow", "Maximum:"))
        self.label_19.setText(_translate("MainWindow", "Current:"))
        self.maxHumFeild.setText(_translate("MainWindow", "TextLabel"))
        self.windDirectFeild.setText(_translate("MainWindow", "TextLabel"))
        self.windSpeedFeild.setText(_translate("MainWindow", "TextLabel"))
        self.label_25.setText(_translate("MainWindow", "Direction:"))
        self.label_26.setText(_translate("MainWindow", "Gust:"))
        self.label_27.setText(_translate("MainWindow", "Average:"))
        self.windGustFeild.setText(_translate("MainWindow", "TextLabel"))
        self.minTempFeild.setText(_translate("MainWindow", "TextLabel"))
        self.currentTempFeild.setText(_translate("MainWindow", "TextLabel"))
        self.label_11.setText(_translate("MainWindow", "Minimum:"))
        self.label_10.setText(_translate("MainWindow", "Maximum:"))
        self.label_9.setText(_translate("MainWindow", "Current:"))
        self.maxTempFeild.setText(_translate("MainWindow", "TextLabel"))
        self.nightRainFeild.setText(_translate("MainWindow", "TextLabel"))
        self.label_22.setText(_translate("MainWindow", "Day:"))
        self.dayRainFeild.setText(_translate("MainWindow", "TextLabel"))
        self.label_23.setText(_translate("MainWindow", "Night:"))
        self.label.setText(_translate("MainWindow", "Date and Time"))
        self.label_2.setText(_translate("MainWindow", "stuff?"))
        self.pushButton_6.setText(_translate("MainWindow", "OK"))
        self.pushButton_7.setText(_translate("MainWindow", "Reset"))
        self.label_8.setText(_translate("MainWindow", "Settings"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionDashboard.setText(_translate("MainWindow", "Dashboard"))
        self.actionDaily_Graphs.setText(_translate("MainWindow", "Daily Graphs"))
        self.actionWeekly_Graphs.setText(_translate("MainWindow", "Weekly Graphs"))
        self.actionYearly_Graphs.setText(_translate("MainWindow", "Yearly Graphs"))
        self.actionAll_Time_Graphs.setText(_translate("MainWindow", "All Time Graphs"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

from pyqtgraph import PlotWidget
